swagger: '2.0'
info:
  title: Devon Example
  description: Example of a API definition
  version: 1.0.0
host: 'localhost:8081'
schemes:
  - https
basePath: /devonfw-server/services/rest
paths:
  '/sampledatamanagement/v1/sampledata/{id}/':
    get:
      summary: Show SampleData
      description: Get a SampleData by his ID
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          type: number
          format: long
          minimum: 0
          required: true
      responses:
        '200':
          description: An SampleDataETO object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /sampledatamanagement/v1/sampledata/:
    post:
      summary: Show SampleData
      description: Get a SampleData by his ID
      parameters:
        - name: sampledata
          in: body
          required: true
          schema:
            $ref: '#/definitions/SampleData'
      responses:
        '200':
          description: An SampleDataETO object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  SampleData:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique identifier representing a specific SampleData
      name:
        type: string
        description: Name string.
      surname:
        type: string
        description: Surname string.
      age:
        type: integer
        format: int32
        description: Age integer
      mail:
        type: string
        description: Mail string.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
