swagger: '2.0'
info:
  title: Devon Example
  description: Example of a API definition
  version: 1.0.0
host: 'localhost:8081'
schemes:
  - https
basePath: /devonfw-server/services/rest
paths:
  /sampledatamanagement/v1/sampledata/{id}/:
    get:
      summary: 'Delegates to {@link Sampledatamanagement#findSampleData}.'
      description: Get a SampleData by his ID.
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          minimum: 0
          maximum: 100
          required: true
      responses:
        '200':
          description: An SampleDataETO object
          schema:
            $ref: '#/definitions/SampleData'
  /sampledatamanagement/v1/sampledata/:
    post:
      summary: 'Delegates to {@link Sampledatamanagement#saveSampleData}.'
      description: Save a SampleData into de DB
      parameters:
        - name: sampledata
          in: body
          required: true
          schema:
            $ref: '#/definitions/SampleData'
      responses:
        '200':
          description: An SampleDataETO object.
  /sampledatamanagement/v1/sampledata/search/:
    post:
      summary: 'Delegates to {@link Moredatamanagement#findMoreDataEtos}.'
      description: Return SampleData that fits the filter.
      parameters:
        - name: filter
          in: body
          required: true
          schema:
            $ref: '#/definitions/SampleData'
      responses:
        '200':
          description: List of SampleData's.
          schema:
            $ref: '#/definitions/ListSampleData'
  '/sampledatamanagement/v1/sampledata/{id}':
    delete:
      summary: 'Delegates to {@link Sampledatamanagement#deleteSampleData}.'
      description: Deletes an existen SampleData from his ID.
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          type: number
          format: long
          minimum: 0
          maximum: 100
          required: true
      responses:
        '200':
          description: SampleData deleted.
definitions:
  ListSampleData:
    type: array
    items:
      $ref: '#definitions/SampleData'
  SampleData:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique identifier representing a specific SampleData
      name:
        type: string
        description: Name string.
      surname:
        type: string
        description: Surname string.
      age:
        type: integer
        format: int32
        description: Age integer.
      mail:
        type: string
        description: Mail string.
  ForTypeExamples:
    type: object
    properties:
      integer:
        description: int example.
        type: integer
        format: int32
      long:
        description: long example.
        type: integer
        format: int64
      float:
        description: float example.
        type: number
        format: float
      double:
        description: double example.
        type: number
        format: double
      string:
        description: string example.
        type: string
      byte:
        description: byte example.
        type: string
        format: byte
      binary:
        description: binary example.
        type: string
        format: binary
      boolean:
        description: boolean example.
        type: boolean
      date:
        description: Date example.
        type: string
        format: date
      dateTime:
        description: dateTime example.
        type: string
        format: date-time
      password:
        description: password example.
        type: string
        format: password
