openapi: 3.0.0
servers:
  - url: 'https://localhost:8081/devonfw-server/services/rest'
info:
  title: Devon Example
  description: Example of a API definition
  version: 1.0.0
paths:
  '/sampledatamanagement/v1/sampledata/{id}/':
    get:
      summary: 'Delegates to {@link Sampledatamanagement#findSampleData}.'
      description: Get a SampleData by his ID.
      operationId: findSampleData
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: An SampleDataETO object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleData'
    delete:
      summary: 'Delegates to {@link Sampledatamanagement#deleteSampleData}.'
      description: Deletes an existent SampleData from his ID.
      operationId: deleteSampleData
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: An SampleDataETO object
  /sampledatamanagement/v1/sampledata/:
    post:
      summary: 'Delegates to {@link Sampledatamanagement#saveSampleData}.'
      description: Save a SampleData into de DB
      operationId: saveSampleData
      responses:
        '200':
          description: An SampleDataETO object.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleData'
      requestBody:
        $ref: '#/components/requestBodies/SampleData'
      tags:
       - paginated
  /sampledatamanagement/v1/sampledata/search/:
    post:
      summary: 'Delegates to {@link Moredatamanagement#findMoreDataEtos}.'
      description: Return SampleData that fits the filter.
      operationId: findSampleDataEtos
      responses:
        '200':
          description: List of SampleData's.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleData'
      requestBody:
        $ref: '#/components/requestBodies/SampleData'
      tags:
        - searchCriteria
        - paginated
  /sampledatamanagement/v1/sampledata/custom/{id}:
    get:
      operationId: customMethod
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: Custom Method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleData'
components:
  schemas:
    SampleData:
      title: sampledatamanagement
      type: object
      description: Description of the object
      properties:
        id:
          type: integer
          format: int64
          minimum: 4
          maximum: 100
          description: Unique identifier representing a specific SampleData
        name:
          type: string
          maxLength: 100
          minLength: 0
          description: Name string.
        surname:
          type: string
          description: Surname string.
        age:
          type: integer
          format: int32
          description: Age integer.
        mail:
          type: string
          description: Mail string.
      required:
        - id
        - name
    MoreData:
      title: moredatamanagement
      type: object
      properties:
        example:
          type: string
  requestBodies:
    SampleData:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sample'
      required: true