openapi: 3.0.0
servers:
  - url: 'https://localhost:8081/devonfw-server/services/rest'
info:
  title: Devon Example
  description: Example of a API definition
  version: 1.0.0
paths:
  '/sampledatamanagement/v1/sampledata/{id}/':
    get:
      summary: 'Delegates to {@link Sampledatamanagement#findSampleData}.'
      description: Get a SampleData by his ID.
      operationId: getSample
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: An SampleDataETO object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleData'
    delete:
      summary: 'Delegates to {@link Sampledatamanagement#deleteSampleData}.'
      description: Deletes an existen SampleData from his ID.
      operationId: deleteSample
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            format: int64
            minimum: 0
            maximum: 100
      responses:
        '200':
          description: An SampleDataETO object
  /sampledatamanagement/v1/sampledata/:
    post:
      summary: 'Delegates to {@link Sampledatamanagement#saveSampleData}.'
      description: Save a SampleData into de DB
      operationId: saveSample
      responses:
        '200':
          description: An SampleDataETO object.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleData'
      requestBody:
        $ref: '#/components/requestBodies/SampleData'
      tags:
       - paginated
  /sampledatamanagement/v1/sampledata/search/:
    post:
      summary: 'Delegates to {@link Moredatamanagement#findMoreDataEtos}.'
      description: Return SampleData that fits the filter.
      operationId: findSampleEtos
      responses:
        '200':
          description: List of SampleData's.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleData'
      requestBody:
        $ref: '#/components/requestBodies/SampleData'
      tags:
        - searchCriteria
        - paginated
components:
  schemas:
    SampleData:
      title: sampledatamanagement
      type: object
      description: Description of the object
      properties:
        id:
          type: integer
          format: int64
          minimum: 4
          maximum: 100
          description: Unique identifier representing a specific SampleData
        name:
          type: string
          maxLength: 100
          minLength: 0
          description: Name string.
        surname:
          type: string
          description: Surname string.
        age:
          type: integer
          format: int32
          description: Age integer.
        mail:
          type: string
          description: Mail string.
        data:
          maximum: 100
          $ref: '#/components/schemas/ModeData'
        tableList:
          type: array
          items:
            $ref: '#/components/schemas/ModeData'
      required:
        - id
        - name
    ModeData:
      title: moredatamanagement
      type: object
      properties:
        example:
          type: string
    Table:
      title: sampledatamanagement
      type: object
      properties:
        example:
          type: string
  requestBodies:
    SampleData:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SampleData'
      required: true